server:
  port: 8081

spring:
  liquibase:
    enabled: false

  datasource:
    driverClassName: org.postgresql.Driver
    # url: jdbc:postgresql://localhost:5434/attr_micro_attraction_db
    url: jdbc:postgresql://localhost:5433/attractions_db
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true