CREATE TABLE cities
(
    ID bigint NOT NULL,
    NAME VARCHAR(30) NOT NULL,
    POPULATION INT NOT NULL,
    SUBWAY BOOLEAN NOT NULL,
    UNIQUE (NAME),
    PRIMARY KEY (ID)
);

CREATE TABLE attractions
(
    ID bigint NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    CREATE_DATE DATE,
    DESCRIBTION TEXT,
    KIND VARCHAR(40) NOT NULL,
    CITY_ID BIGINT NOT NULL,
    UNIQUE (NAME),
    PRIMARY KEY (ID),
    CONSTRAINT FK_ATTRACTIONS FOREIGN KEY (CITY_ID)
        REFERENCES cities (ID)
);

CREATE TABLE excursions
(
    ID bigint NOT NULL,
    NAME VARCHAR(60) NOT NULL,
    DESCRIBTION TEXT,
    UNIQUE (NAME),
    PRIMARY KEY (ID)
);

CREATE TABLE ATTRACTIONS_EXCURSIONS
(
    ATTRACTION_ID BIGINT NOT NULL,
    EXCURSION_ID BIGINT NOT NULL,
    PRIMARY KEY (ATTRACTION_ID, EXCURSION_ID),
    CONSTRAINT FK_ATTRACTIONS_EXCURSIONS FOREIGN KEY (ATTRACTION_ID)
        REFERENCES attractions (ID) ,
    CONSTRAINT FK_EXCURSIONS_ATTRACTIONS FOREIGN KEY (EXCURSION_ID)
        REFERENCES excursions (ID)
)