
INSERT INTO cities (ID, NAME, POPULATION, SUBWAY) VALUES (1, 'Samara', 1158952, 'TRUE');
INSERT INTO cities (ID, NAME, POPULATION, SUBWAY) VALUES (2, 'Moscow', 13149803, 'TRUE');
INSERT INTO cities (ID, NAME, POPULATION, SUBWAY) VALUES (3, 'St. Petersburg', 5597763, 'TRUE');
INSERT INTO cities (ID, NAME, POPULATION, SUBWAY) VALUES (4, 'Novosibirsk', 1633851, 'TRUE');

INSERT INTO cities (ID, NAME, POPULATION, SUBWAY) VALUES (5, 'Yekaterinburg', 1536183, 'TRUE');
INSERT INTO cities (ID, NAME, POPULATION, SUBWAY) VALUES (6, 'Kazan', 1318604, 'TRUE');
INSERT INTO cities (ID, NAME, POPULATION, SUBWAY) VALUES (7, 'Krasnoyarsk', 1205473, 'FALSE');
INSERT INTO cities (ID, NAME, POPULATION, SUBWAY) VALUES (8, 'Nizhny Novgorod', 1204985, 'TRUE');

INSERT INTO cities (ID, NAME, POPULATION, SUBWAY) VALUES (9, 'Chelyabinsk', 1177058, 'FALSE' );
INSERT INTO cities (ID, NAME, POPULATION, SUBWAY) VALUES (10, 'Ufa', 1163304, 'FALSE');
INSERT INTO cities (ID, NAME, POPULATION, SUBWAY) VALUES (11, 'Rostov na Don', 1140487, 'FALSE');
INSERT INTO cities (ID, NAME, POPULATION, SUBWAY) VALUES (12, 'Krasnodar', 1138654, 'FALSE');

INSERT INTO cities (ID, NAME, POPULATION, SUBWAY) VALUES (13, 'Omsk', 1104485, 'FALSE');
INSERT INTO cities (ID, NAME, POPULATION, SUBWAY) VALUES (14, 'Voronezh', 1046425, 'FALSE');
INSERT INTO cities (ID, NAME, POPULATION, SUBWAY) VALUES (15, 'Perm', 1026908, 'FALSE');
INSERT INTO cities (ID, NAME, POPULATION, SUBWAY) VALUES (16, 'Volgograd', 1018898, 'FALSE');