-- Samara id 1
INSERT INTO ATTRACTIONS_EXCURSIONS (ATTRACTION_ID, EXCURSION_ID) VALUES (1, 1);
INSERT INTO ATTRACTIONS_EXCURSIONS (ATTRACTION_ID, EXCURSION_ID) VALUES (2, 1);
INSERT INTO ATTRACTIONS_EXCURSIONS (ATTRACTION_ID, EXCURSION_ID) VALUES (3, 1);
-- Moscow id 2
INSERT INTO ATTRACTIONS_EXCURSIONS (ATTRACTION_ID, EXCURSION_ID) VALUES (4, 2);
INSERT INTO ATTRACTIONS_EXCURSIONS (ATTRACTION_ID, EXCURSION_ID) VALUES (5, 2);
INSERT INTO ATTRACTIONS_EXCURSIONS (ATTRACTION_ID, EXCURSION_ID) VALUES (6, 2);
-- St. Petersburg id 3
INSERT INTO ATTRACTIONS_EXCURSIONS (ATTRACTION_ID, EXCURSION_ID) VALUES (7, 2);
INSERT INTO ATTRACTIONS_EXCURSIONS (ATTRACTION_ID, EXCURSION_ID) VALUES (8, 2);
INSERT INTO ATTRACTIONS_EXCURSIONS (ATTRACTION_ID, EXCURSION_ID) VALUES (9, 2);
-- Novosibirsk id 4
INSERT INTO ATTRACTIONS_EXCURSIONS (ATTRACTION_ID, EXCURSION_ID) VALUES (10, 3);
INSERT INTO ATTRACTIONS_EXCURSIONS (ATTRACTION_ID, EXCURSION_ID) VALUES (11, 3);
INSERT INTO ATTRACTIONS_EXCURSIONS (ATTRACTION_ID, EXCURSION_ID) VALUES (12, 3);
-- Yekaterinburg id 5
INSERT INTO ATTRACTIONS_EXCURSIONS (ATTRACTION_ID, EXCURSION_ID) VALUES (13, 3);
INSERT INTO ATTRACTIONS_EXCURSIONS (ATTRACTION_ID, EXCURSION_ID) VALUES (14, 3);
INSERT INTO ATTRACTIONS_EXCURSIONS (ATTRACTION_ID, EXCURSION_ID) VALUES (15, 3);
-- Kazan id 6
INSERT INTO ATTRACTIONS_EXCURSIONS (ATTRACTION_ID, EXCURSION_ID) VALUES (16, 1);
INSERT INTO ATTRACTIONS_EXCURSIONS (ATTRACTION_ID, EXCURSION_ID) VALUES (17, 1);
INSERT INTO ATTRACTIONS_EXCURSIONS (ATTRACTION_ID, EXCURSION_ID) VALUES (18, 1);
-- Krasnoyarsk id 7
INSERT INTO ATTRACTIONS_EXCURSIONS (ATTRACTION_ID, EXCURSION_ID) VALUES (19, 3);
INSERT INTO ATTRACTIONS_EXCURSIONS (ATTRACTION_ID, EXCURSION_ID) VALUES (20, 3);
INSERT INTO ATTRACTIONS_EXCURSIONS (ATTRACTION_ID, EXCURSION_ID) VALUES (21, 3);
--Nizhny Novgorod id 8
INSERT INTO ATTRACTIONS_EXCURSIONS (ATTRACTION_ID, EXCURSION_ID) VALUES (22, 1);
INSERT INTO ATTRACTIONS_EXCURSIONS (ATTRACTION_ID, EXCURSION_ID) VALUES (23, 1);
INSERT INTO ATTRACTIONS_EXCURSIONS (ATTRACTION_ID, EXCURSION_ID) VALUES (24, 1);
-- Chelyabinsk id 9
INSERT INTO ATTRACTIONS_EXCURSIONS (ATTRACTION_ID, EXCURSION_ID) VALUES (25, 4);
INSERT INTO ATTRACTIONS_EXCURSIONS (ATTRACTION_ID, EXCURSION_ID) VALUES (26, 4);
INSERT INTO ATTRACTIONS_EXCURSIONS (ATTRACTION_ID, EXCURSION_ID) VALUES (27, 4);
-- Ufa id 10
INSERT INTO ATTRACTIONS_EXCURSIONS (ATTRACTION_ID, EXCURSION_ID) VALUES (28, 1);
INSERT INTO ATTRACTIONS_EXCURSIONS (ATTRACTION_ID, EXCURSION_ID) VALUES (29, 1);
INSERT INTO ATTRACTIONS_EXCURSIONS (ATTRACTION_ID, EXCURSION_ID) VALUES (30, 1);
-- Rostov na Don id 11
INSERT INTO ATTRACTIONS_EXCURSIONS (ATTRACTION_ID, EXCURSION_ID) VALUES (31, 5);
INSERT INTO ATTRACTIONS_EXCURSIONS (ATTRACTION_ID, EXCURSION_ID) VALUES (32, 5);
INSERT INTO ATTRACTIONS_EXCURSIONS (ATTRACTION_ID, EXCURSION_ID) VALUES (33, 5);
-- Krasnodar id 12
INSERT INTO ATTRACTIONS_EXCURSIONS (ATTRACTION_ID, EXCURSION_ID) VALUES (34, 5);
INSERT INTO ATTRACTIONS_EXCURSIONS (ATTRACTION_ID, EXCURSION_ID) VALUES (35, 5);
INSERT INTO ATTRACTIONS_EXCURSIONS (ATTRACTION_ID, EXCURSION_ID) VALUES (36, 5);
-- Omsk id 13
INSERT INTO ATTRACTIONS_EXCURSIONS (ATTRACTION_ID, EXCURSION_ID) VALUES (37, 3);
INSERT INTO ATTRACTIONS_EXCURSIONS (ATTRACTION_ID, EXCURSION_ID) VALUES (38, 3);
INSERT INTO ATTRACTIONS_EXCURSIONS (ATTRACTION_ID, EXCURSION_ID) VALUES (39, 3);
-- Voronezh id 14
INSERT INTO ATTRACTIONS_EXCURSIONS (ATTRACTION_ID, EXCURSION_ID) VALUES (40, 1);
INSERT INTO ATTRACTIONS_EXCURSIONS (ATTRACTION_ID, EXCURSION_ID) VALUES (41, 1);
INSERT INTO ATTRACTIONS_EXCURSIONS (ATTRACTION_ID, EXCURSION_ID) VALUES (42, 1);
-- Perm id 15
INSERT INTO ATTRACTIONS_EXCURSIONS (ATTRACTION_ID, EXCURSION_ID) VALUES (43, 4);
INSERT INTO ATTRACTIONS_EXCURSIONS (ATTRACTION_ID, EXCURSION_ID) VALUES (44, 4);
INSERT INTO ATTRACTIONS_EXCURSIONS (ATTRACTION_ID, EXCURSION_ID) VALUES (45, 4);
-- Volgograd id 16
INSERT INTO ATTRACTIONS_EXCURSIONS (ATTRACTION_ID, EXCURSION_ID) VALUES (46, 5);
INSERT INTO ATTRACTIONS_EXCURSIONS (ATTRACTION_ID, EXCURSION_ID) VALUES (47, 5);
INSERT INTO ATTRACTIONS_EXCURSIONS (ATTRACTION_ID, EXCURSION_ID) VALUES (48, 5);